version: "3.8"

services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - :$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  server:
    depends_on:
      - mongo_db
    extends:
      file: ../SocsakBackend/docker-compose.yml
      service: server
    env_file: ./.env

  client:
    depends_on:
      - server
    extends:
      file: ../SocsakFrontend/docker-compose.yml
      service: client
    env_file: ./.env

volumes:
  db: