version: "3.8"

services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  server:
    depends_on:
      - mongo_db
    build: ../SocsakBackend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $SPRINT_LOCAL_SOCKET_PORT:$SPRING_DOCKER_SOCKET_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
        }'
      jwt-secret: $JWT_SECRET
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  client:
    extends:
      file: ../SocsakFrontend/docker-compose.yml
      service: client
    env_file: ./.env
    ports:
      - $SVE_LOCAL_PORT:$SVE_DOCKER_PORT

volumes:
  db: